services:
  recipe-app:
    build: .
    container_name: madhacks-recipe-app
    volumes:
      - ./recipeIn.csv:/app/recipeIn.csv
      - ./recipeOut.csv:/app/recipeOut.csv
      - ./templates:/app/templates
    stdin_open: true
    tty: true

  caddy:
    image: caddy:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/usr/share/caddy/html
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - recipe-app