version: '3.8'

services:
  recipe-app:
    build: .
    container_name: madhacks-recipe-app
    volumes:
      - ./recipeIn.csv:/app/recipeIn.csv
      - ./recipeOut.csv:/app/recipeOut.csv
    stdin_open: true
    tty: true